### PR TITLE
Fix: videos menu rendering conditions + add shorcut explanation in settings

### LINKED ISSUE #625: Missing Shortcut in Settings
The shortcut triggered by `V` is not listed in the shortcuts section under settings. `V` opens the list of episodes. Should it be added?

### PR DESCRIPTION
**Pull request by kKaskak**

### CODE REVIEW

File: src/routes/Player/Player.js [hunk 1]
```diff
@@ -533,7 +533,7 @@ const Player = ({ urlParams, queryParams }) => {
                 }
                 case 'KeyV': {
                     closeMenus();
-                    if (player.metaItem !== null && player.metaItem.type === 'Ready') {
+                    if (player.metaItem !== null && player.metaItem.type === 'Ready' && player.metaItem.content.type === 'series') {
```
Comment (tymmesyde) [inline src/routes/Player/Player.js]: It should check if it has videos instead of the type

**Review by tymmesyde — APPROVED** [review]
